### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by zmechu** [Ananaskirsche/ts-csgo-rankbot#1]
Hello!

Your script is what I'm looking for :-)
But how to use it? Put in into server?

Regards!

**Comment by Ananaskirsche** [comment]
I was going to write an setup manual once I have released a first version. At the time of writing it is not ready for usage since key elements are not working properly or need further improvements.

**Comment by zmechu** [comment]
OK, thanks for quick answer!

When (+/-) you plan to release "ready to use" script? :-)

Regards!

**Comment by Ananaskirsche** [comment]
I merged the development branch into the master yesterday which already contained a lot of improvements. So (without promising) a first version should be ready in about a week.

**Comment by zmechu** [comment]
Thanks, I keep my finger crossed :-)
