### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by szogi1910** [Ananaskirsche/ts-csgo-rankbot#2]
I have a small problem running this.
I read another report and I know that you still have to wait for the working version

`SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
`

**Comment by Ananaskirsche** [comment]
It is very little information to work with. I have googled the error message and it seems to me that the error occures because of an outdated version of NodeJS. I am using Node 12.10.0 for development. Can you please check your version and update if so?

**Comment by szogi1910** [comment]
I checked my version
 node -v
v12.10.0

**Comment by szogi1910** [comment]
Okay, I'm going ahead some new error logs

`Error: Cannot find module 'ts3-nodejs-library'
Require stack:
- /xxx/xxx/csgorank/teamspeak.js
- /xxx/xxx/csgorank/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
    at Function.Module._load (internal/modules/cjs/loader.js:677:27)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/xxx/xxx/csgorank/teamspeak.js:1:21)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/xxx/xxx/csgorank/teamspeak.js',
    '/xxx/xxx/csgorank/index.js'
  ]
}
`

**Comment by Ananaskirsche** [comment]
Seems like the module is not installed. Did you run `npm run`?

**Comment by szogi1910** [comment]
hmm...

`0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/root/.nvm/versions/node/v12.10.0/bin/node',
1 verbose cli   '/root/.nvm/versions/node/v12.10.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'package.json'
1 verbose cli ]
2 info using npm@6.10.3
3 info using node@v12.10.0
4 verbose stack Error: missing script: package.json
4 verbose stack     at run (/root/.nvm/versions/node/v12.10.0/lib/node_modules/npm/lib/run-script.js:155:19)
4 verbose stack     at /root/.nvm/versions/node/v12.10.0/lib/node_modules/npm/lib/run-script.js:63:5
4 verbose stack     at /root/.nvm/versions/node/v12.10.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:115:5
4 verbose stack     at /root/.nvm/versions/node/v12.10.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:418:5
4 verbose stack     at checkBinReferences_ (/root/.nvm/versions/node/v12.10.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:373:45)
4 verbose stack     at final (/root/.nvm/versions/node/v12.10.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:416:3)
4 verbose stack     at then (/root/.nvm/versions/node/v12.10.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:160:5)
4 verbose stack     at ReadFileContext.<anonymous> (/root/.nvm/versions/node/v12.10.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:332:20)
4 verbose stack     at ReadFileContext.callback (/root/.nvm/versions/node/v12.10.0/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:90:16)
4 verbose stack     at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:250:13)
5 verbose cwd /home/teamspeak/csgorank
6 verbose Linux 4.4.0-159-generic
7 verbose argv "/root/.nvm/versions/node/v12.10.0/bin/node" "/root/.nvm/versions/node/v12.10.0/bin/npm" "run" "package.json"
8 verbose node v12.10.0
9 verbose npm  v6.10.3
10 error missing script: package.json
11 verbose exit [ 1, true ]
`

**Comment by szogi1910** [comment]
After several attempts I still don't want to install the module

The npm run command returns no message

**Comment by Ananaskirsche** [comment]
Can you please run the following command for me in the directory where you have downloaded the files. The output you sent clearly indicates, that the ts3-nodejs-library is missing and with the pastebin link I got via e-mail (which seems to be missing here) it says that the package.json file is missing.
`tree -L 2 .`

EDIT: It had to be `npm install` instead of `npm rum`. My bad.

**Comment by szogi1910** [comment]
Applications were successfully launched, unfortunately, the package.json file did not add all the modules that I manually added using
npm install winston | npm install ts3-nodejs-library | npm install xmldoc

Thank you for your help, I think the thread can be closed
