### ISSUE TITLE
Multilingual file and a welcome message

### ISSUE THREAD

**Issue by szogi1910** [Ananaskirsche/ts-csgo-rankbot#3]
Are you able to add a translation file of individual messages that the bot sends on tsie?
I do not know if this is feasible, but whether people who connected their Steam-TS3 accounts did not have to receive messages from the bot every time after entering the ts3 server.

**Comment by Ananaskirsche** [comment]
I was going to implement multilingual messages. But at the moment I am looking for some kind of API.
For people not getting a welcome message if they have already connected their identity, is (in my opinion) a point which could be added later on too. Multilanguage support is more important to me.

**Comment by szogi1910** [comment]
I have another idea ...
Sending commands to the chat channel to verify the rank on it :)

**Comment by Ananaskirsche** [comment]
So multilanguage support is now added. About your other idea I have to think a bit because I personally don't think that it's a good idea to just bind the bot to every channel.

**Comment by szogi1910** [comment]
Just define on what channel.
Thanks for making changes.

//Edit
Polish translation

`{
  "register_command_help_text": "!register - Połącz swoją tożsamość TS ze swoim profilem Steam",
  "status_command_help_text": "!status - Sprawdź czy jesteś zarejestrowany",
  "update_command_help_text": "!update - Natychmiast sprawdza, czy Twoja ranga się zmieniła",
  "register_command_help_usage": "!register <link do profilu steam>",
  "wrong_profile_url": "Twój adres URL profilu jest nieprawidłowy!",
  "add_bot": "Dodaj [url=%s]bota[/url] do znajomych!",
  "registered": "Jesteś zarejestrowany! Użyj polecenia !update, aby natychmiast zaktualizować swoją rangę!",
  "not_registered": "Nie jesteś jeszcze zarejestrowany! Użyj polecenia !register, aby powiązać swoją tożsamość TS ze swoim profilem Steam!",
  "already_registered": "Jesteś już zarejestrowany, użyj polecenia !update aby zaaktualizować swoją rangę!"
}`

**Comment by Ananaskirsche** [comment]
> Just define on what channel.
Thanks for making changes.

Thats a good idea, will have a look at that

Btw, thank you for creating a polish translation. Next time please create a pull request. I will add the pull request manually for you this time ;)

**Comment by Acu1ty** [comment]
@szogi1910
 Hi how can i start the bot?
